### ISSUE TITLE
facebook login 연동

### ISSUE THREAD

**Issue by underlinee** [bong-dragon/cowlib-server#1]

**Comment by dragonist** [comment]
localhost:8080/ 하면 index.html 내려줌

index.html 에서 facebook 로그인 버튼 누르면, 
팝업창으로 localhost:8080/connect/facebook (post) 요청을 함

페북 로그인이 완료되면 토큰이 저장되고 
resources://connect/facebookConnected.html 내려줌

facebookConnected.html에서 팝업창을 킨 부모(index.html)을 새로고침 하게 하고 자기 자신은 close

> 따라서 index.html 에서 login 되어있는지 refresh 될때 한번만 조사하면 될듯!
> url 은 localhost:8080/auth 로 로그인 되어있으면 사용자 정보를 json 형태로 줌
